//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainerApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get unlimited ammunition for all weapons, and never need to reload any weapon again..
        /// </summary>
        public static string strChkCheatDescriptionInfiniteAmmo {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlimited money for buying stuff!.
        /// </summary>
        public static string strChkCheatDescriptionInfiniteCredits {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your heath never decreases..
        /// </summary>
        public static string strChkCheatDescriptionInfiniteHP {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get unlimited power nodes to upgrade your weapons and gear!.
        /// </summary>
        public static string strChkCheatDescriptionInfinitePowerNodes {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfinitePowerNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use your stasis module unlimitedly..
        /// </summary>
        public static string strChkCheatDescriptionInfiniteStasis {
            get {
                return ResourceManager.GetString("strChkCheatDescriptionInfiniteStasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Ammo + No Reload:.
        /// </summary>
        public static string strChkCheatPromptInfiniteAmmo {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Credits:.
        /// </summary>
        public static string strChkCheatPromptInfiniteCredits {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite HP:.
        /// </summary>
        public static string strChkCheatPromptInfiniteHP {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Power Nodes:.
        /// </summary>
        public static string strChkCheatPromptInfinitePowerNodes {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfinitePowerNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Stasis:.
        /// </summary>
        public static string strChkCheatPromptInfiniteStasis {
            get {
                return ResourceManager.GetString("strChkCheatPromptInfiniteStasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available hacks.
        /// </summary>
        public static string strGroupBoxHeaderCheats {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game info.
        /// </summary>
        public static string strGroupBoxHeaderGameInfo {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us!.
        /// </summary>
        public static string strGroupBoxHeaderSupport {
            get {
                return ResourceManager.GetString("strGroupBoxHeaderSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click to donate via PayPal)..
        /// </summary>
        public static string strLblClickToDonate {
            get {
                return ResourceManager.GetString("strLblClickToDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game&apos;s process:.
        /// </summary>
        public static string strLblGamesProcessPrompt {
            get {
                return ResourceManager.GetString("strLblGamesProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not detected... Please, run the game!.
        /// </summary>
        public static string strLblNotAttached {
            get {
                return ResourceManager.GetString("strLblNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID:.
        /// </summary>
        public static string strLblProcessIDPrompt {
            get {
                return ResourceManager.GetString("strLblProcessIDPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, consider supporting the developer!.
        /// </summary>
        public static string strLblRequestForDonation {
            get {
                return ResourceManager.GetString("strLblRequestForDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required game version:.
        /// </summary>
        public static string strLblRequiredGameVersionPrompt {
            get {
                return ResourceManager.GetString("strLblRequiredGameVersionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.0.0.222 (Steam).
        /// </summary>
        public static string strLblRequiredGameVersionValue {
            get {
                return ResourceManager.GetString("strLblRequiredGameVersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMvader-DeadSpace by Vinicius.RAS.
        /// </summary>
        public static string strMainWindowTitle {
            get {
                return ResourceManager.GetString("strMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach to the game&apos;s process!.
        /// </summary>
        public static string strMsgFailedToAttach {
            get {
                return ResourceManager.GetString("strMsgFailedToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach.
        /// </summary>
        public static string strMsgFailedToAttachCaption {
            get {
                return ResourceManager.GetString("strMsgFailedToAttachCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NONE&gt;.
        /// </summary>
        public static string strNoneTag {
            get {
                return ResourceManager.GetString("strNoneTag", resourceCulture);
            }
        }
    }
}
